# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# Nome do workflow no repositório
name: Integração continua de Java com Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Jobs do ambiente de desenvolvimento
  build-dev:
    # Runner com uma instância do ubuntu  
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps:
    # Utiliza a action checkout para fazer o git clone no runner    
    - name: Realiza o checkout do repositório
      uses: actions/checkout@v3
    # Utiliza a action setup-java para configurar a versão necessária do JDK
    - name: Configura o JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    # Executa a compilação do projeto com o Maven no runner 
    - name: Compila o projeto com Maven
      run: mvn -B compile --file pom.xml
  
  # Jobs do ambiente de homologação
  build-hmg:            
    # Runner com uma instância da matriz
    runs-on: ${{ matrix.os }}       
    # Nome do Job no workflow
    name: build-hmg - SO ${{ matrix.os }} e JDK ${{matrix.java}}... 
    environment: 
      name: hmg
    needs: build-dev    
    # Prepara diversas versões do SO e do Java
    strategy:
      fail-fast: false
      matrix:        
        #os: [ubuntu-latest, macos-latest, windows-latest]  
        os: [ubuntu-latest, macos-latest]          
        java: [16, 17, 18]        
    steps:
    # Utiliza a action checkout para fazer o git clone no runner    
    - name: Realiza o checkout do repositório
      uses: actions/checkout@v3 
      with:
        fetch-depth: 0 
    # Utiliza a action setup-java para configurar a versão necessária do JDK
    - name: Configura o JDK ${{matrix.java}}
      uses: actions/setup-java@v3      
      with:        
        distribution: 'temurin'
        java-version: ${{matrix.java}}
        cache: maven
    # Executa o teste do projeto com o Maven no runner    
    - name: Testa o projeto com Maven
      run: mvn -B test --file pom.xml
      
    # Executa os passos da análise do código com o sonarcube     
    - name: Cache dos pacotes do SonarCloud
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    # Configura um cache as dependências do projeto, isso vai permitir 
    # que as próximas execuções do workflow sejam mais rápidas visto 
    # que as dependências já estarão disponibilizadas para o runner
    - name: Cache dos pacotes do Maven
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    # Executa a verificação do projeto com o Maven no runner    
    - name: Verifica o projeto com Maven e Jacoco
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.coverage.jacoco.xmlReportPaths='target/site/jacoco/jacoco.xml' -Dsonar.projectKey=osmarbraz_figuras_teste5_so
      #run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=osmarbraz_figuras_teste5_so
            
  # Jobs do ambiente de produção
  build-prd:
    # Runner com uma instância do ubuntu        
    runs-on: ubuntu-latest
    environment: 
      name: prd
    needs: build-hmg
    steps:
    # Utiliza a action checkout para fazer o git clone no runner    
    - name: Realiza o checkout do repositório
      uses: actions/checkout@v3
    # Utiliza a action setup-java para configurar a versão necessária do JDK
    - name: Configura o JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    # Executa o empacotamento do projeto com o Maven no runner    
    # O parâmetro -DskipTests pula os testes pois já foram executados no ambiente anterior.
    - name: Empacota o projeto com Maven      
      run: mvn -B package --file pom.xml -DskipTests
    # Cria o artefato de download    
    - name: Crie uma pasta temporária de downloads de artefatos
      run: mkdir staging
    - name: Copia os artefatos a serem publicados na pasta temporária
      run: cp target/*jar-with-dependencies.jar staging
    - name: Usa Upload Artifact do GitHub Action
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging      